version: '3.8'

services:
  backend:
    build: ./BackEnd
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - krakend-net

  krakend:
    image: devopsfaith/krakend:2.4
    container_name: krakend
    ports:
      - "8080:8080"
    volumes:
      - ./krakend/krakend.json:/etc/krakend/krakend.json
    depends_on:
      - backend
    networks:
      - krakend-net

networks:
  krakend-net:
    driver: bridge
